### ISSUE TITLE
Überschreiben der Zeit funktioniert nicht mehr

### ISSUE THREAD

**Issue by stefanfitzi** [alv-ch/alv-ch-sysinfos.api#20]
- Zwischenfall eröffnen – Zwischenfall abschliessen  ->  ok
- Zwischenfall eröffnen – Updatemeldung - Zeit von wird überschrieben – abschliessen – Start und Ende bis wird mit der Systemzeit abgefüllt
Dieses Verhalten ist m.E. erst seit dem Deployment vom 19.06.

- Abschluss Wartungsmeldung wird ebenfalls bei Start und Ende mit der Systemzeit überschrieben

**Comment by stefanfitzi** [comment]
Was ist genau das Problem? Ich habe es durchgespielt und der Start enthält nach Abschluss die Systemzeit, zu der ich die Meldung eröffnet habe (16:05) und das Ende die Systemzeit, zu der ich die Meldung abgeschlossen habe (16:07):
Start:       21.06.2017 - 16:05 Uhr
Ende:	21.06.2017 - 16:07 Uhr

Ist das nicht das gewünschte Verhalten?

**Comment by J-Dummermuth** [comment]
Das Problem war, dass die Eigenschaft "gültig von" durch Informationupdates überschrieben wurde. 
"Gültig von" sollte aber weiterhin die Systemzeit zu der die Message erstellt wurde beinhalten.
Ist gefixt.
