### ISSUE TITLE
Übersetzungen ergänzen

### ISSUE THREAD

**Issue by stefanfitzi** [alv-ch/alv-ch-sysinfos.api#22]
Die im angehängten File aufgeführten Übersetzungen sind nachzupflegen:
[translations.docx](https://github.com/alv-ch/alv-ch-sysinfos.api/files/1091328/translations.docx)

**Comment by stefanfitzi** [comment]
Diesen Punkt hat Martin aus meiner Sicht bereits umgesetzt.

**Comment by dvoracek-martin** [comment]
All translations, which I've received till now, were implemented
