### ISSUE TITLE
You have to change the status to "Informationsupdate" to be able to update the incident

### ISSUE THREAD

**Issue by J-Kaempfer** [alv-ch/alv-ch-sysinfos.api#29]
If you don't change the status to "Informationsupdate" you get an second "Eröfnungsmeldung" instead of an "Updatemeldung". For every change in the incident, you have to change the status otherwise you should get an error message.

**Comment by stefanfitzi** [comment]
Fixed the whole template selection etc. So this one should also be fixed...
