### ISSUE TITLE
If you made an "Informationsupdate" successfully, the status falls to "Problem wird analysiert" back

### ISSUE THREAD

**Issue by J-Kaempfer** [alv-ch/alv-ch-sysinfos.api#30]
If I updated the incident, the status "Informationsupdate" should't fall back on "Problem wird analysiert".

This happens only if you change the date.  If you only change the "informationsupdate" it works correct.

**Comment by J-Dummermuth** [comment]
Ich kann den Bug bei mir nicht reproduzieren und gehe somit davon aus, dass dieser bereits durch den Fix eines anderen Issues behoben wurde.
