### ISSUE TITLE
To update the incident, an "informationsupdate" is required.

### ISSUE THREAD

**Issue by J-Kaempfer** [alv-ch/alv-ch-sysinfos.api#34]
The "informationsupdate" is required, to change the time for the next information is not required.

**Comment by stefanfitzi** [comment]
I don't understand, what is the reported problem. Please explain what is expected and what is the application currently doing.

**Comment by J-Kaempfer** [comment]
If I open a new Incidetent, the "Eröffnungsmeldung" is sent correct. When I later change the time for the next Information but NOT the status. A second "Eröffnungsmeldung" for the same incident is sent.

In every case when the user changed somthing in the incident, the status must be change to "Informatiosupdate". Otherwise it should display an errormessage.

**Comment by stefanfitzi** [comment]
Thanks for the additional info.
In this case the problem has been fixed together with the other issues concerning the templates.
