### ISSUE TITLE
Technical Dept - Wahl des Templates erfolgt via Array-Index

### ISSUE THREAD

**Issue by stefanfitzi** [alv-ch/alv-ch-sysinfos.api#38]
In message.js  ->  $scope.refreshPreview  (Zeile 1023)
erfolgt die Wahl des Templates basierend auf dem Array-Index. Der Array wird aus den Resultaten der Db-Query abgefüllt. Dies scheint mir etwas heikel. Was ist, wenn aus irgendeinem Grund die Reihenfolge der Resultate der Db-Query ändert?
Aus meiner Sicht sollten wir die Wahl eher basierend auf der Db-Id (analog prepareTemplates() in Zeile 227) machen.

**Comment by dvoracek-martin** [comment]
implementiert
