### ISSUE TITLE
Kontaktformular vervollständigen

### ISSUE THREAD

**Issue by rohrtom** [alv-ch/alv-ch-sysinfos.api#39]
Eidgenössisches Departement für
Wirtschaft, Bildung und Forschung WBF
Staatssekretariat für Wirtschaft SECO
Arbeitsmarkt/Arbeitslosenversicherung
TCIT Informatik

Finkenhubelweg 12
CH - 3012 Bern

Postadresse:
Holzikofenweg 36
CH - 3003 Bern

+4158 480 61 71

(mailto)servicedesk@alv.admin.ch
(href)http://www.seco.admin.ch

**Comment by stefanfitzi** [comment]
Wenn ich im Menü "Kontakt" wähle, sehe ich genau diese Angaben. Hier eine Kopie:
Eidgenössisches Departement für
Wirtschaft, Bildung und Forschung WBF
Staatssekretariat für Wirtschaft SECO
Arbeitsmarkt/Arbeitslosenversicherung
TCIT Informatik

Finkenhubelweg 12 
CH - 3012 Bern
Postadresse: Holzikofenweg 36, 3003 Bern 

Telefon: +4158 480 61 71
servicedesk@alv.admin.ch 
www.seco.admin.ch

**Comment by stefanfitzi** [comment]
Sehe nicht, was ergänzt werden müsste.
