### ISSUE TITLE
Wartungsfenster Endzeit

### ISSUE THREAD

**Issue by rohrtom** [alv-ch/alv-ch-sysinfos.api#44]
Die Endzeit des Wartungsfensters wird bei manuellem Abschluss nicht richtig gesetzt. Nach dem Deployment kann ein Wartungsfenster nicht mehr abgeschlossen oder storniert werden. Die Funktionalität lief vor dem Deployment!

**Comment by stefanfitzi** [comment]
Das Sperren des Wartungsfenster-Abschlusses ist dann, wenn die aktuelle Zeit noch VOR der Startzeit des Wartungsfensters liegt. Dies ist ein sinnvolles Verhalten, weil man ein Wartungsfenster nicht abschliessen kann, bevor es überhaupt begonnen hat (dann müsste man es eher canceln).
Ist aus meiner Sicht also kein Bug, sondern korrektes Verhalten der Businesslogik. Sobald die aktuelle Zeit die Startzeit überschritten hat und man die Seite mit den Meldungsdetails aktualisiert, erscheint die Option zum Abschliessen des Wartungsfensters.
Auch die Zeit wird dann korrekt gesetzt.

**Comment by stefanfitzi** [comment]
Rollback zu Version vor dem Deployment und anschliessend fixen des Problems, dass die Endzeit beim manuellen Abschluss nicht korrekt gesetzt wird.
