### ISSUE TITLE
Falsche Erfolgsmeldung wenn nur Schweregrad geändert wird

### ISSUE THREAD

**Issue by stefanfitzi** [alv-ch/alv-ch-sysinfos.api#51]
Wenn ich Status auf "Problem wird analysiert" belasse und nur den Schweregrad verändere und "Meldung aktualisieren" drücke, erscheint die Erfolgsmeldung:
"Der Mitteilungsstatus wurde erfolgreich zu "Problem wird analysiert" geändert."

**Comment by stefanfitzi** [comment]
Prio 2, ist nicht so tragisch

**Comment by J-Dummermuth** [comment]
Dasselbe geschieht auch wenn man bloss den Zeitpunkt der nächsten Information verändert.

**Comment by dvoracek-martin** [comment]
Fixed after changing rules of validation. User is now able to change any information in STATUS_CHANGED state only
