### ISSUE TITLE
Wenn Mail-Server nicht verfügbar, gehen die Mails "verloren"

### ISSUE THREAD

**Issue by stefanfitzi** [alv-ch/alv-ch-sysinfos.api#53]
Während meinen Tests war ich kurz offline (deshalb war der Mailserver natürlich nicht erreichbar). Im Log finde ich folgende Fehlermeldung:

[WARN] ch.alv.sysinfos.service.internal.DefaultMailSenderService - E-mail could not be sent to user '[stefan.fitzi@bafnpo.org]', exception is: Mail server connection failed; nested exception is com.sun.mail.util.MailConnectException: Couldn't connect to host, port: mail.bafnpo.org, 587; timeout -1;
  ....

Die Mails werden danach nicht mehr versendet.

**Comment by dvoracek-martin** [comment]
..is IMHO not a bug - the behavior was always like that. Even though I need to admit that it's kinda odd.

**Comment by stefanfitzi** [comment]
Has been fixed together with issue #28 .
